### ISSUE TITLE
Backend - Options data

### ISSUE THREAD

**Issue by ricardoprins** [ricardoprins/stockinator#12]
Basically is to edit the python backend to retrieve stock options data.

PS: Wanna know what options are? [click here to know more](https://www.investopedia.com/articles/optioninvestor/03/073003.asp)

**Comment by koolgax99** [comment]
sir can you explain more about this too in technical terms

**Comment by ricardoprins** [comment]
Sure. Currently, we have a simple backend interface using a small FastAPI file (see backend folder). However, we need to expand the robustness of the API, adding the functionality of pulling options data as well.

**Comment by koolgax99** [comment]
Oh I saw the file and I can work on this under your guidance. Can you please assign it to me and also give the suitable ref links.

**Comment by ricardoprins** [comment]
Perfect. Please reach out to me on whatsapp (+13852015229) 

I'm excited to work together in this task :D
