### ISSUE TITLE
CODE OF CONDUCT file and contributing file

### ISSUE THREAD

**Issue by akrish4** [ricardoprins/stockinator#34]
Hi @ricardoprins 
I would like to contribute to this project , I found that there is no contributing.md file and code_of_conduct.md file , kindly assign me , I can make a well documented and formatted files and will also update README file accordingly

**Comment by ricardoprins** [comment]
Hi! I've assigned it to you.

**Comment by akrish4** [comment]
Hi @ricardoprins 
Kindly do add the DWOC tag also since this project is registered under DWOC.

**Comment by akrish4** [comment]
Hi @ricardoprins 
I have worked 
#36  PR

**Comment by ricardoprins** [comment]
Thanks for your contribution!
