### ISSUE TITLE
Add Contributors.md File

### ISSUE THREAD

**Issue by muthuannamalai12** [ricardoprins/stockinator#37]
Hai,
I would like to add Contributors.md file in your project in the form of a table and display a link to it in README.md

**Comment by muthuannamalai12** [comment]
I would love to work on this issue as a part of DWOC. Kindly assign me this issue.

**Comment by ricardoprins** [comment]
Sure, go ahead!

**Comment by muthuannamalai12** [comment]
I have created a pull request. Kindly review it
