### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by ricardoprins** [ricardoprins/stockinator#4]

**Comment by BlakeLof** [comment]
![537f4d6d-6006-421e-b66c-3e42656deef0_200x200](https://user-images.githubusercontent.com/59660821/95374936-d0ba0a00-0893-11eb-86b0-0bee1a07977c.png)

**Comment by ricardoprins** [comment]
Hey, maybe you could upload it to a folder named 'media' or something like that...what do you think?
