### ISSUE TITLE
Integrate Welcome and Greeting Bot 

### ISSUE THREAD

**Issue by akrish4** [ricardoprins/stockinator#40]
Hi @ricardoprins 
I would like to contribute to this project by adding a welcome and greeting bot which will comment up when any user will open up with an issue or pull-request for the first time 
Kindly do assign me this issue @ricardoprins  
( config file having a proper message) 

For reference, kindly check out: https://github.com/apps/welcome

**Comment by ricardoprins** [comment]
Sure, go ahead!

**Comment by akrish4** [comment]
#50  PR
