### ISSUE TITLE
Add Contributions Table in README.md

### ISSUE THREAD

**Issue by samir-0711** [ricardoprins/stockinator#48]
## 📚 Documentation

I want to add contributors table where all contributors will be shown.
Like this
![image](https://user-images.githubusercontent.com/68433936/104547935-bb543900-5655-11eb-9919-e01b9664e3bf.png)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/ricardoprins/stockinator/blob/master/CONTRIBUTION.md)?

Yes

**Comment by samir-0711** [comment]
I would like to work on this.

**Comment by ricardoprins** [comment]
Sure, go ahead!
