### ISSUE TITLE
README FILE BADGES  

### ISSUE THREAD

**Issue by akrish4** [ricardoprins/stockinator#49]
## 🚀 Feature

I would like to add badges to the repository README which will give better look and make it look interesting 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/ricardoprins/stockinator/blob/master/CONTRIBUTION.md)?

(Write your answer here.)
yes 
## Motivation

self-motivation 

## Pitch

I can add badges using shield.io and it will give a new look similar to the below image  

![readme1](https://user-images.githubusercontent.com/61831021/104577343-64635980-567f-11eb-9cef-713c04114d45.PNG)

Kindly do assign me this issue and also a better label for my work :)

**Comment by ricardoprins** [comment]
Alright!

**Comment by akrish4** [comment]
Kindly assign

**Comment by ricardoprins** [comment]
Sorry, I thought I did it before. It should be fine now!

**Comment by akrish4** [comment]
yeah fine 
thank you @ricardoprins

**Comment by akrish4** [comment]
#53   PR
