### ISSUE TITLE
Rearrange Documentation

### ISSUE THREAD

**Issue by LeeRenJie** [ricardoprins/stockinator#67]
## 📚 Documentation
*Under DWOC
Rearrange the README.md file

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/ricardoprins/stockinator/blob/master/CONTRIBUTION.md)?
Yes
(Write your answer here.)
![image](https://user-images.githubusercontent.com/67599130/107363522-3efa2c00-6b15-11eb-9133-ad2202d289fa.png)
I would like to align this to the middle.

I would also like to rearrange the readme.md file into this arrangement(based on title):
1. Story and Concept🖋
1. What is a Stock Screener? 🔎
1. Project Details 📕
1. How to Contribute?
1. Contact info 📞
1. Discord server
1. Open-source Programs👾
1. Our Contributors 👩🏻‍🤝‍🧑🏼

And also update the contributor table if needed.

**Comment by ricardoprins** [comment]
Sure, go ahead!
